services:
  - type: web
    name: my-python-app
    env: docker
    plan: free  # Change this to 'starter' or 'standard' based on your needs
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8501
    buildCommand: ""  # Dockerfile already handles installation
    startCommand: "python app2.py"  # Align with the Docker CMD