services:
  - type: web
    name: my-python-app
    env: docker
    plan: free  # Change this to 'starter' or 'standard' if needed
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8501